### ISSUE TITLE
Integration removed entities

### ISSUE THREAD

**Issue by JoryHogeveen** [magtimmermans/home-assistant-sensor-luchtmeetnet#4]
It seems not all entities are loaded anymore.
Just updated HACS and HA recently and the existing entities were removed.

- `sensor.luchtmeetnet_air_quality_index`
- `sensor.luchtmeetnet_air_quality_status`

In fact, I cannot find any entities related to this integration anymore..

**Comment by Obsidi88** [comment]
I was seeing something similar, turns out it was a 'duplicated mapping key' in my configuration.yaml
I had inadvertently made this interfere with the Afvalbeheer HACS integration by pippyn.

As both this and Afvalbeheer require the sensor added to configuration.yaml in a similar method using the sensor key, I was overwriting the luchtmeetnet one.

I had this:

```
sensor:
  - platform: luchtmeetnet
    name: 'LuchtMeetNet'
sensor:
 - platform: afvalbeheer
   wastecollector: hvc
   resources:
   - restafval
   - gft
   - papier
   - pmd
```

I changed it to be:

```
sensor:
 - platform: afvalbeheer
   wastecollector: hvc
   resources:
   - restafval
   - gft
   - papier
 - platform: luchtmeetnet
    name: 'LuchtMeetNet'
```

And now it loads!

This thread helped:
https://community.home-assistant.io/t/multiple-sensors-in-configuration-yaml-configurator-notes-duplicated-mapping-key-but-passes-configuration-check/195115
